# Workflow based on the w3c/spec-prod action example for multi-spec repos:
# https://github.com/w3c/spec-prod/blob/main/docs/examples.md#multiple-specs-in-same-repository

name: Build, Validate, Deploy and Publish

on:
  # Worflow runs on pull requests where it makes sure that the spec can still be
  # generated, that markup is valid and that there are no broken links, as
  # well as on pushes to the default branch where it also deploys the generated
  # spec to the gh-pages branch and publishes the result to /TR.
  # The "workflow_dispatch" hook allows admins to also trigger the workflow
  # manually from GitHub's UI.
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - source: index.src.html
            destination: index.html
            echidna_token: ECHIDNA_TOKEN_WEBCODECS
            build_override: |
              status: WD
          - source: codec_registry.src.html
            destination: codec_registry.html
            echidna_token: ECHIDNA_TOKEN_REGISTRY
            build_override: |
              status: NOTE-WD
          - source: avc_codec_registration.src.html
            destination: avc_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_AVC_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: vorbis_codec_registration.src.html
            destination: vorbis_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_VORBIS_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: mp3_codec_registration.src.html
            destination: mp3_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_MP3_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: aac_codec_registration.src.html
            destination: aac_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_AAC_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: flac_codec_registration.src.html
            destination: flac_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_FLAC_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: opus_codec_registration.src.html
            destination: opus_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_OPUS_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: av1_codec_registration.src.html
            destination: av1_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_AV1_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: vp9_codec_registration.src.html
            destination: vp9_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_VP9_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: vp8_codec_registration.src.html
            destination: vp8_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_VP8_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: pcm_codec_registration.src.html
            destination: pcm_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_PCM_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: alaw_codec_registration.src.html
            destination: alaw_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_ALAW_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: ulaw_codec_registration.src.html
            destination: ulaw_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_ULAW_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: hevc_codec_registration.src.html
            destination: hevc_codec_registration.html
            echidna_token: ECHIDNA_TOKEN_HEVC_REGISTRATION
            build_override: |
              status: NOTE-WD
          - source: video_frame_metadata_registry.src.html
            destination: video_frame_metadata_registry.html
            echidna_token: ECHIDNA_TOKEN_VIDEOFRAMEMETADATA_REGISTRY
            build_override: |
              status: DRY
    steps:
      # See doc at https://github.com/actions/checkout#checkout-v2
      - name: Checkout repository
        uses: actions/checkout@v2

      # See doc at https://github.com/w3c/spec-prod/#spec-prod
      # The action only deploys the generated spec to the gh-pages branch when
      # the workflow was triggered by a push to the default branch.
      - name: Build and validate index.html, push to gh-pages branch if needed
        uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
          BUILD_FAIL_ON: nothing
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets[matrix.echidna_token] }}
          W3C_WG_DECISION_URL: https://github.com/w3c/media-wg/issues/27
          W3C_BUILD_OVERRIDE: ${{ matrix.build_override }}
